Zorbus\BlockBundle\Entity\Block:
    type: entity
    table: zorbus_block_block
    repositoryClass: Zorbus\BlockBundle\Entity\BlockRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        service:
            type: string
            length: 255
            nullable: false
        category:
            type: string
            length: 255
            nullable: true
        parameters:
            type: text
            default: {}
            nullable: true
        theme:
            type: string
            length: 255
            default: default
            nullable: true
        lang:
            type: string
            length: 5
            default: en_US
            nullable: true
        cache_ttl:
            type: integer
            default: 0
            nullable: true
        enabled:
            type: boolean
            default: true
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update