zorbus_block_config:
    pattern:  /block/config/{type}
    defaults: { _controller: ZorbusBlockBundle:Default:config }
zorbus_block_show:
    pattern:  /block/config/{id}/show
    defaults: { _controller: ZorbusBlockBundle:Default:show }
    requirements:
        id: \d+