parameters:
    zorbus_block.compiler.config.class: Zorbus\BlockBundle\DependencyInjection\Compiler\BlockCompilerConfig

    zorbus_block.block.admin.class: Zorbus\BlockBundle\Admin\BlockAdmin

    zorbus_block.block.entity.class: Zorbus\BlockBundle\Entity\Block

    zorbus_block.block.controller.class: ZorbusBlockBundle:Admin\Block

    zorbus_block.service.text.class: Zorbus\BlockBundle\Model\BlockTextConfig
    zorbus_block.service.rss.class: Zorbus\BlockBundle\Model\BlockRssConfig

services:
    zorbus_block.block.admin:
        class: %zorbus_block.block.admin.class%
        arguments: [~, %zorbus_block.block.entity.class%, %zorbus_block.block.controller.class%]
        calls:
            - [setTranslationDomain, [BlockBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pages, label: Blocks }
    zorbus_block.compiler.config:
        class: %zorbus_block.compiler.config.class%
        scope: prototype
    zorbus_block.service.text:
        class: %zorbus_block.service.text.class%
        scope: prototype
        arguments: ['@zorbus_block.block.admin', '@templating', '@form.factory']
        tags:
            - { name: zorbus_block.block, category: Text }
    zorbus_block.service.rss:
        class: %zorbus_block.service.rss.class%
        scope: prototype
        arguments: ['@zorbus_block.block.admin', '@templating', '@form.factory']
        tags:
            - { name: zorbus_block.block, category: Text }
